"""Observed WotS constructor defaults; TDB 82, capture 2026-09-28.

Only constructor_after samples are included. Unknown fields stay unresolved.
Values are not guaranteed across game builds.
"""

CAPTURE_SOURCE = 'wots_timeline_defaults_20260928_181302.json'

CONSTRUCTOR_DEFAULTS = {'app.motion_track.AttackCollision_Body': {'AlwaysHitStopParamID': {'declared_type': 'System.Int32',
                                                                    'value': 0},
                                           'AttackParamID': {'declared_type': 'System.UInt32',
                                                             'value': 0},
                                           'AttackVecDir': {'declared_type': 'System.Int32',
                                                            'value': 1424599936},
                                           'DamageDispEndFlag': {'declared_type': 'System.Boolean',
                                                                 'value': False},
                                           'DisableDetectAttack': {'declared_type': 'System.Boolean',
                                                                   'value': False},
                                           'HitStopID': {'declared_type': 'System.Int32',
                                                         'value': 0},
                                           'OnClipBox.On': {'declared_type': 'System.Boolean',
                                                            'value': True},
                                           'OnClipBox.RawOn': {'declared_type': 'System.Boolean',
                                                               'value': False},
                                           'On_AlwaysHitStop': {'declared_type': 'System.Boolean',
                                                                'value': False},
                                           'ReachPatternIDOverride': {'declared_type': 'System.Int32',
                                                                      'value': -1},
                                           'RequestSetID': {'declared_type': 'System.UInt32',
                                                            'value': 0},
                                           'SoulGenerateOverwriteParam.GenerateMoveType': {'declared_type': 'System.Int32',
                                                                                           'value': 3},
                                           'VfxOverwriteParam.AdditionalBreakableVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                                   'value': False},
                                           'VfxOverwriteParam.AdditionalBreakableVfx.On': {'declared_type': 'System.Boolean',
                                                                                           'value': False},
                                           'VfxOverwriteParam.AdditionalBreakableVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                                'value': True},
                                           'VfxOverwriteParam.AdditionalElementVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                                 'value': False},
                                           'VfxOverwriteParam.AdditionalElementVfx.On': {'declared_type': 'System.Boolean',
                                                                                         'value': False},
                                           'VfxOverwriteParam.AdditionalElementVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                              'value': True},
                                           'VfxOverwriteParam.AdditionalNormalHitVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                                   'value': False},
                                           'VfxOverwriteParam.AdditionalNormalHitVfx.On': {'declared_type': 'System.Boolean',
                                                                                           'value': False},
                                           'VfxOverwriteParam.AdditionalNormalHitVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                                'value': True},
                                           'VfxOverwriteParam.AdditionalSoulGenerateVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                                      'value': False},
                                           'VfxOverwriteParam.AdditionalSoulGenerateVfx.On': {'declared_type': 'System.Boolean',
                                                                                              'value': False},
                                           'VfxOverwriteParam.AdditionalSoulGenerateVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                                   'value': True},
                                           'VfxOverwriteParam.AdditionalVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                          'value': False},
                                           'VfxOverwriteParam.AdditionalVfx.On': {'declared_type': 'System.Boolean',
                                                                                  'value': False},
                                           'VfxOverwriteParam.AdditionalVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                       'value': True},
                                           'VfxOverwriteParam.BaseVfx.On': {'declared_type': 'System.Boolean',
                                                                            'value': False},
                                           'VfxOverwriteParam.BloodTrail.On': {'declared_type': 'System.Boolean',
                                                                               'value': False},
                                           'VfxOverwriteParam.DlcAdditionalHitVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                                'value': False},
                                           'VfxOverwriteParam.DlcAdditionalHitVfx.On': {'declared_type': 'System.Boolean',
                                                                                        'value': False},
                                           'VfxOverwriteParam.DlcAdditionalHitVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                             'value': True},
                                           'VfxOverwriteParam.Position.On': {'declared_type': 'System.Boolean',
                                                                             'value': False},
                                           'VfxOverwriteParam.Position.Random': {'declared_type': 'System.Boolean',
                                                                                 'value': False},
                                           'VfxOverwriteParam.Position.RandomValue': {'declared_type': 'System.Single',
                                                                                      'value': 0.0},
                                           'VfxOverwriteParam.Position.UseJointConst': {'declared_type': 'System.Boolean',
                                                                                        'value': False},
                                           'VfxOverwriteParam.Rotation.On': {'declared_type': 'System.Boolean',
                                                                             'value': False},
                                           'VfxOverwriteParam.Rotation.Random': {'declared_type': 'System.Boolean',
                                                                                 'value': False},
                                           'VfxOverwriteParam.Scale.On': {'declared_type': 'System.Boolean',
                                                                          'value': False},
                                           'VfxOverwriteParam.Scale.Random': {'declared_type': 'System.Boolean',
                                                                              'value': False},
                                           'VfxOverwriteParam.Scale.RandomValue': {'declared_type': 'System.Single',
                                                                                   'value': 0.0},
                                           'VfxOverwriteParam.Scale.Value': {'declared_type': 'System.Single',
                                                                             'value': 1.0}},
 'app.motion_track.AttackCollision_Wp': {'AlwaysHitStopParamID': {'declared_type': 'System.Int32',
                                                                  'value': 0},
                                         'AttackParamID': {'declared_type': 'System.UInt32',
                                                           'value': 0},
                                         'AttackVecDir': {'declared_type': 'System.Int32',
                                                          'value': 1424599936},
                                         'CollisionType': {'declared_type': 'System.UInt32',
                                                           'value': 0},
                                         'DamageDispEndFlag': {'declared_type': 'System.Boolean',
                                                               'value': False},
                                         'DisableDetectAttack': {'declared_type': 'System.Boolean',
                                                                 'value': False},
                                         'HitStopID': {'declared_type': 'System.Int32', 'value': 0},
                                         'OnClipBox.On': {'declared_type': 'System.Boolean',
                                                          'value': True},
                                         'OnClipBox.RawOn': {'declared_type': 'System.Boolean',
                                                             'value': False},
                                         'On_AlwaysHitStop': {'declared_type': 'System.Boolean',
                                                              'value': False},
                                         'ReachPatternIDOverride': {'declared_type': 'System.Int32',
                                                                    'value': -1},
                                         'RequestSetID': {'declared_type': 'System.UInt32',
                                                          'value': 0},
                                         'SoulGenerateOverwriteParam.GenerateMoveType': {'declared_type': 'System.Int32',
                                                                                         'value': 3},
                                         'VfxOverwriteParam.AdditionalBreakableVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                                 'value': False},
                                         'VfxOverwriteParam.AdditionalBreakableVfx.On': {'declared_type': 'System.Boolean',
                                                                                         'value': False},
                                         'VfxOverwriteParam.AdditionalBreakableVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                              'value': True},
                                         'VfxOverwriteParam.AdditionalElementVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                               'value': False},
                                         'VfxOverwriteParam.AdditionalElementVfx.On': {'declared_type': 'System.Boolean',
                                                                                       'value': False},
                                         'VfxOverwriteParam.AdditionalElementVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                            'value': True},
                                         'VfxOverwriteParam.AdditionalNormalHitVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                                 'value': False},
                                         'VfxOverwriteParam.AdditionalNormalHitVfx.On': {'declared_type': 'System.Boolean',
                                                                                         'value': False},
                                         'VfxOverwriteParam.AdditionalNormalHitVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                              'value': True},
                                         'VfxOverwriteParam.AdditionalSoulGenerateVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                                    'value': False},
                                         'VfxOverwriteParam.AdditionalSoulGenerateVfx.On': {'declared_type': 'System.Boolean',
                                                                                            'value': False},
                                         'VfxOverwriteParam.AdditionalSoulGenerateVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                                 'value': True},
                                         'VfxOverwriteParam.AdditionalVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                        'value': False},
                                         'VfxOverwriteParam.AdditionalVfx.On': {'declared_type': 'System.Boolean',
                                                                                'value': False},
                                         'VfxOverwriteParam.AdditionalVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                     'value': True},
                                         'VfxOverwriteParam.BaseVfx.On': {'declared_type': 'System.Boolean',
                                                                          'value': False},
                                         'VfxOverwriteParam.BloodTrail.On': {'declared_type': 'System.Boolean',
                                                                             'value': False},
                                         'VfxOverwriteParam.DlcAdditionalHitVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                              'value': False},
                                         'VfxOverwriteParam.DlcAdditionalHitVfx.On': {'declared_type': 'System.Boolean',
                                                                                      'value': False},
                                         'VfxOverwriteParam.DlcAdditionalHitVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                                           'value': True},
                                         'VfxOverwriteParam.Position.On': {'declared_type': 'System.Boolean',
                                                                           'value': False},
                                         'VfxOverwriteParam.Position.Random': {'declared_type': 'System.Boolean',
                                                                               'value': False},
                                         'VfxOverwriteParam.Position.RandomValue': {'declared_type': 'System.Single',
                                                                                    'value': 0.0},
                                         'VfxOverwriteParam.Position.UseJointConst': {'declared_type': 'System.Boolean',
                                                                                      'value': False},
                                         'VfxOverwriteParam.Rotation.On': {'declared_type': 'System.Boolean',
                                                                           'value': False},
                                         'VfxOverwriteParam.Rotation.Random': {'declared_type': 'System.Boolean',
                                                                               'value': False},
                                         'VfxOverwriteParam.Scale.On': {'declared_type': 'System.Boolean',
                                                                        'value': False},
                                         'VfxOverwriteParam.Scale.Random': {'declared_type': 'System.Boolean',
                                                                            'value': False},
                                         'VfxOverwriteParam.Scale.RandomValue': {'declared_type': 'System.Single',
                                                                                 'value': 0.0},
                                         'VfxOverwriteParam.Scale.Value': {'declared_type': 'System.Single',
                                                                           'value': 1.0}},
 'app.motion_track.CameraEvent': {'CameraAutoFollowDisable': {'declared_type': 'System.Boolean',
                                                              'value': True},
                                  'CameraLockOnDisable': {'declared_type': 'System.Boolean',
                                                          'value': True},
                                  'CameraParamSetting.AimingEnable': {'declared_type': 'System.Boolean',
                                                                      'value': False},
                                  'CameraParamSetting.IsDeadParam': {'declared_type': 'System.Boolean',
                                                                     'value': False},
                                  'CameraParamSetting.OnlyLockOnEnable': {'declared_type': 'System.Boolean',
                                                                          'value': False},
                                  'CameraParamSetting.OverrideLockOnParam': {'declared_type': 'System.Boolean',
                                                                             'value': False},
                                  'CameraParamSetting.OverrideLockOnParamIndex': {'declared_type': 'System.Int32',
                                                                                  'value': 0},
                                  'CameraParamSetting.TimeFrame': {'declared_type': 'System.Single',
                                                                   'value': 0.0},
                                  'CameraShakeSetting.AttackCheck': {'declared_type': 'System.Boolean',
                                                                     'value': False},
                                  'CameraShakeSetting.CameraShakeTime': {'declared_type': 'System.Single',
                                                                         'value': 0.0},
                                  'CameraShakeSetting.ShakeEveryHit': {'declared_type': 'System.Boolean',
                                                                       'value': False},
                                  'CameraShakeSetting.ShakeJoint.Hash': {'declared_type': 'System.UInt32',
                                                                         'value': 0},
                                  'CameraWorkContinueFlag': {'declared_type': 'System.Boolean',
                                                             'value': False},
                                  'CameraWorkSetting.ContinueFlag': {'declared_type': 'System.Boolean',
                                                                     'value': False},
                                  'CameraWorkSetting.IgnoreInBattle': {'declared_type': 'System.Boolean',
                                                                       'value': False},
                                  'CameraWorkSetting.OnlyIgnorInSingleBattle': {'declared_type': 'System.Boolean',
                                                                                'value': False},
                                  'CameraWorkSetting.OnlyIgnorInSquaBattle': {'declared_type': 'System.Boolean',
                                                                              'value': False},
                                  'CameraWorkSetting.UseLookAtObj': {'declared_type': 'System.Boolean',
                                                                     'value': False}},
 'app.motion_track.CharacterBasic': {'MotionSpeed': {'declared_type': 'System.Single',
                                                     'value': 1.0},
                                     'OverrideStandState': {'declared_type': 'System.Int32',
                                                            'value': 0},
                                     'RotationRate': {'declared_type': 'System.Single',
                                                      'value': 1.0},
                                     'TranslateRate': {'declared_type': 'System.Single',
                                                       'value': 1.0},
                                     'WeaponBasic.HideWeaponAll': {'declared_type': 'System.Boolean',
                                                                   'value': False}},
 'app.motion_track.CharacterDirectDamageTrack': {'AttackParamID': {'declared_type': 'System.UInt32',
                                                                   'value': 0},
                                                 'AttackVecDir': {'declared_type': 'System.Int32',
                                                                  'value': 1424599936},
                                                 'Damage': {'declared_type': 'System.Boolean',
                                                            'value': False},
                                                 'DamageDispEndFlag': {'declared_type': 'System.Boolean',
                                                                       'value': False},
                                                 'DirectHitID': {'declared_type': 'System.Int32',
                                                                 'value': 0},
                                                 'DisableDetectAttack': {'declared_type': 'System.Boolean',
                                                                         'value': False},
                                                 'FixedMeshCutID': {'declared_type': 'System.Int32',
                                                                    'value': -1},
                                                 'HitStopID': {'declared_type': 'System.Int32',
                                                               'value': 0},
                                                 'HitTrailAttachInfo.On': {'declared_type': 'System.Boolean',
                                                                           'value': False},
                                                 'HitTrailAttachInfo.WeaponType': {'declared_type': 'System.Int32',
                                                                                   'value': 15},
                                                 'IsFixedMeshCutAttackerDirFollow': {'declared_type': 'System.Boolean',
                                                                                     'value': False},
                                                 'SelfDamage': {'declared_type': 'System.Boolean',
                                                                'value': False},
                                                 'SoulGenerateOverwriteParam.GenerateMoveType': {'declared_type': 'System.Int32',
                                                                                                 'value': 3},
                                                 'TargetIndex': {'declared_type': 'System.Int32',
                                                                 'value': 0}},
 'app.motion_track.CharacterGrappleTrack': {'ConstKey.BlendRate': {'declared_type': 'System.Single',
                                                                   'value': 0.0},
                                            'ConstKey.BlendTargetJointInfo.IsOn': {'declared_type': 'System.Boolean',
                                                                                   'value': False},
                                            'ConstKey.IgnoreAttachGround': {'declared_type': 'System.Boolean',
                                                                            'value': False},
                                            'ConstKey.JointInfo.IsOn': {'declared_type': 'System.Boolean',
                                                                        'value': False},
                                            'ConstKey.PosRate': {'declared_type': 'System.Single',
                                                                 'value': 0.0},
                                            'ConstKey.PosRateXZ': {'declared_type': 'System.Single',
                                                                   'value': 0.0},
                                            'ConstKey.RotJointInfo.IsOn': {'declared_type': 'System.Boolean',
                                                                           'value': False},
                                            'ConstKey.RotRate': {'declared_type': 'System.Single',
                                                                 'value': 0.0},
                                            'OwnerKey.PhaseFixed': {'declared_type': 'System.Int32',
                                                                    'value': 1646028160}},
 'app.motion_track.CharacterHitStopTrack': {'HitStopAll.AfterFrame': {'declared_type': 'System.Single',
                                                                      'value': 0.0},
                                            'HitStopAll.BeforeFrame': {'declared_type': 'System.Single',
                                                                       'value': 0.0},
                                            'HitStopAll.DisableWristFlip_PL': {'declared_type': 'System.Boolean',
                                                                               'value': False},
                                            'HitStopAll.GuardAfterFrame': {'declared_type': 'System.Single',
                                                                           'value': 0.0},
                                            'HitStopAll.GuardBeforeFrame': {'declared_type': 'System.Single',
                                                                            'value': 0.0},
                                            'HitStopAll.GuardRate': {'declared_type': 'System.Single',
                                                                     'value': 0.0},
                                            'HitStopAll.GuardStopFrame': {'declared_type': 'System.Single',
                                                                          'value': 0.0},
                                            'HitStopAll.HitStopID': {'declared_type': 'System.Int32',
                                                                     'value': 0},
                                            'HitStopAll.On': {'declared_type': 'System.Boolean',
                                                              'value': True},
                                            'HitStopAll.StopFrame': {'declared_type': 'System.Single',
                                                                     'value': 0.0},
                                            'HitStopAll.StopRate': {'declared_type': 'System.Single',
                                                                    'value': 1.0},
                                            'HitStopAllSp.AfterFrame': {'declared_type': 'System.Single',
                                                                        'value': 0.0},
                                            'HitStopAllSp.BeforeFrame': {'declared_type': 'System.Single',
                                                                         'value': 0.0},
                                            'HitStopAllSp.DisableWristFlip_PL': {'declared_type': 'System.Boolean',
                                                                                 'value': False},
                                            'HitStopAllSp.GuardAfterFrame': {'declared_type': 'System.Single',
                                                                             'value': 0.0},
                                            'HitStopAllSp.GuardBeforeFrame': {'declared_type': 'System.Single',
                                                                              'value': 0.0},
                                            'HitStopAllSp.GuardRate': {'declared_type': 'System.Single',
                                                                       'value': 0.0},
                                            'HitStopAllSp.GuardStopFrame': {'declared_type': 'System.Single',
                                                                            'value': 0.0},
                                            'HitStopAllSp.HitStopID': {'declared_type': 'System.Int32',
                                                                       'value': 0},
                                            'HitStopAllSp.On': {'declared_type': 'System.Boolean',
                                                                'value': True},
                                            'HitStopAllSp.StopFrame': {'declared_type': 'System.Single',
                                                                       'value': 0.0},
                                            'HitStopAllSp.StopRate': {'declared_type': 'System.Single',
                                                                      'value': 1.0},
                                            'HitStopOwner.AfterFrame': {'declared_type': 'System.Single',
                                                                        'value': 0.0},
                                            'HitStopOwner.BeforeFrame': {'declared_type': 'System.Single',
                                                                         'value': 0.0},
                                            'HitStopOwner.DisableWristFlip_PL': {'declared_type': 'System.Boolean',
                                                                                 'value': False},
                                            'HitStopOwner.GuardAfterFrame': {'declared_type': 'System.Single',
                                                                             'value': 0.0},
                                            'HitStopOwner.GuardBeforeFrame': {'declared_type': 'System.Single',
                                                                              'value': 0.0},
                                            'HitStopOwner.GuardRate': {'declared_type': 'System.Single',
                                                                       'value': 0.0},
                                            'HitStopOwner.GuardStopFrame': {'declared_type': 'System.Single',
                                                                            'value': 0.0},
                                            'HitStopOwner.HitStopID': {'declared_type': 'System.Int32',
                                                                       'value': 0},
                                            'HitStopOwner.On': {'declared_type': 'System.Boolean',
                                                                'value': True},
                                            'HitStopOwner.StopFrame': {'declared_type': 'System.Single',
                                                                       'value': 0.0},
                                            'HitStopOwner.StopRate': {'declared_type': 'System.Single',
                                                                      'value': 1.0},
                                            'HitStopOwnerTarget.AfterFrame': {'declared_type': 'System.Single',
                                                                              'value': 0.0},
                                            'HitStopOwnerTarget.BeforeFrame': {'declared_type': 'System.Single',
                                                                               'value': 0.0},
                                            'HitStopOwnerTarget.DisableWristFlip_PL': {'declared_type': 'System.Boolean',
                                                                                       'value': False},
                                            'HitStopOwnerTarget.GuardAfterFrame': {'declared_type': 'System.Single',
                                                                                   'value': 0.0},
                                            'HitStopOwnerTarget.GuardBeforeFrame': {'declared_type': 'System.Single',
                                                                                    'value': 0.0},
                                            'HitStopOwnerTarget.GuardRate': {'declared_type': 'System.Single',
                                                                             'value': 0.0},
                                            'HitStopOwnerTarget.GuardStopFrame': {'declared_type': 'System.Single',
                                                                                  'value': 0.0},
                                            'HitStopOwnerTarget.HitStopID': {'declared_type': 'System.Int32',
                                                                             'value': 0},
                                            'HitStopOwnerTarget.On': {'declared_type': 'System.Boolean',
                                                                      'value': True},
                                            'HitStopOwnerTarget.StopFrame': {'declared_type': 'System.Single',
                                                                             'value': 0.0},
                                            'HitStopOwnerTarget.StopRate': {'declared_type': 'System.Single',
                                                                            'value': 1.0},
                                            'HitStopOwnerTargetSp.AfterFrame': {'declared_type': 'System.Single',
                                                                                'value': 0.0},
                                            'HitStopOwnerTargetSp.BeforeFrame': {'declared_type': 'System.Single',
                                                                                 'value': 0.0},
                                            'HitStopOwnerTargetSp.DisableWristFlip_PL': {'declared_type': 'System.Boolean',
                                                                                         'value': False},
                                            'HitStopOwnerTargetSp.GuardAfterFrame': {'declared_type': 'System.Single',
                                                                                     'value': 0.0},
                                            'HitStopOwnerTargetSp.GuardBeforeFrame': {'declared_type': 'System.Single',
                                                                                      'value': 0.0},
                                            'HitStopOwnerTargetSp.GuardRate': {'declared_type': 'System.Single',
                                                                               'value': 0.0},
                                            'HitStopOwnerTargetSp.GuardStopFrame': {'declared_type': 'System.Single',
                                                                                    'value': 0.0},
                                            'HitStopOwnerTargetSp.HitStopID': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                            'HitStopOwnerTargetSp.On': {'declared_type': 'System.Boolean',
                                                                        'value': True},
                                            'HitStopOwnerTargetSp.StopFrame': {'declared_type': 'System.Single',
                                                                               'value': 0.0},
                                            'HitStopOwnerTargetSp.StopRate': {'declared_type': 'System.Single',
                                                                              'value': 1.0},
                                            'HitStopPlEnemy.AfterFrame': {'declared_type': 'System.Single',
                                                                          'value': 0.0},
                                            'HitStopPlEnemy.BeforeFrame': {'declared_type': 'System.Single',
                                                                           'value': 0.0},
                                            'HitStopPlEnemy.DisableWristFlip_PL': {'declared_type': 'System.Boolean',
                                                                                   'value': False},
                                            'HitStopPlEnemy.GuardAfterFrame': {'declared_type': 'System.Single',
                                                                               'value': 0.0},
                                            'HitStopPlEnemy.GuardBeforeFrame': {'declared_type': 'System.Single',
                                                                                'value': 0.0},
                                            'HitStopPlEnemy.GuardRate': {'declared_type': 'System.Single',
                                                                         'value': 0.0},
                                            'HitStopPlEnemy.GuardStopFrame': {'declared_type': 'System.Single',
                                                                              'value': 0.0},
                                            'HitStopPlEnemy.HitStopID': {'declared_type': 'System.Int32',
                                                                         'value': 0},
                                            'HitStopPlEnemy.On': {'declared_type': 'System.Boolean',
                                                                  'value': True},
                                            'HitStopPlEnemy.StopFrame': {'declared_type': 'System.Single',
                                                                         'value': 0.0},
                                            'HitStopPlEnemy.StopRate': {'declared_type': 'System.Single',
                                                                        'value': 1.0},
                                            'HitStopTarget.AfterFrame': {'declared_type': 'System.Single',
                                                                         'value': 0.0},
                                            'HitStopTarget.BeforeFrame': {'declared_type': 'System.Single',
                                                                          'value': 0.0},
                                            'HitStopTarget.DisableWristFlip_PL': {'declared_type': 'System.Boolean',
                                                                                  'value': False},
                                            'HitStopTarget.GuardAfterFrame': {'declared_type': 'System.Single',
                                                                              'value': 0.0},
                                            'HitStopTarget.GuardBeforeFrame': {'declared_type': 'System.Single',
                                                                               'value': 0.0},
                                            'HitStopTarget.GuardRate': {'declared_type': 'System.Single',
                                                                        'value': 0.0},
                                            'HitStopTarget.GuardStopFrame': {'declared_type': 'System.Single',
                                                                             'value': 0.0},
                                            'HitStopTarget.HitStopID': {'declared_type': 'System.Int32',
                                                                        'value': 0},
                                            'HitStopTarget.On': {'declared_type': 'System.Boolean',
                                                                 'value': True},
                                            'HitStopTarget.StopFrame': {'declared_type': 'System.Single',
                                                                        'value': 0.0},
                                            'HitStopTarget.StopRate': {'declared_type': 'System.Single',
                                                                       'value': 1.0}},
 'app.motion_track.CharacterRequestStageGimmick': {'AuxiliaryID': {'declared_type': 'System.Int32',
                                                                   'value': 0},
                                                   'IsRequestCheck': {'declared_type': 'System.Boolean',
                                                                      'value': False},
                                                   'JointInfo.JointHash.Hash': {'declared_type': 'System.UInt32',
                                                                                'value': 0},
                                                   'ReleaseCarryGm': {'declared_type': 'System.Boolean',
                                                                      'value': False}},
 'app.motion_track.CharacterWorkRateChangeTrack': {'WorkRateSetting.PriorityLevel': {'declared_type': 'System.Int32',
                                                                                     'value': 0},
                                                   'WorkRateSetting.Rate': {'declared_type': 'System.Single',
                                                                            'value': 1.0},
                                                   'WorkRateSetting.TargetType': {'declared_type': 'System.Int32',
                                                                                  'value': -1692139776},
                                                   'WorkRateSettingTrigger.AfterFrame': {'declared_type': 'System.Single',
                                                                                         'value': 0.0},
                                                   'WorkRateSettingTrigger.BeforeFrame': {'declared_type': 'System.Single',
                                                                                          'value': 0.0},
                                                   'WorkRateSettingTrigger.Frame': {'declared_type': 'System.Single',
                                                                                    'value': 0.0},
                                                   'WorkRateSettingTrigger.PriorityLevel': {'declared_type': 'System.Int32',
                                                                                            'value': 0},
                                                   'WorkRateSettingTrigger.Rate': {'declared_type': 'System.Single',
                                                                                   'value': 1.0},
                                                   'WorkRateSettingTrigger.TargetType': {'declared_type': 'System.Int32',
                                                                                         'value': -1692139776}},
 'app.motion_track.EnemyActionTransitionTrack': {'DieFadeOut': {'declared_type': 'System.Boolean',
                                                                'value': True},
                                                 'DieTransition.InterpolationFrame': {'declared_type': 'System.Int32',
                                                                                      'value': 5},
                                                 'DieTransition.MotionType': {'declared_type': 'System.Int32',
                                                                              'value': -1},
                                                 'DieTransition.StartFrame': {'declared_type': 'System.Single',
                                                                              'value': 0.0},
                                                 'RikidoBreakTransition.InterpolationFrame': {'declared_type': 'System.Int32',
                                                                                              'value': 5},
                                                 'RikidoBreakTransition.MotionType': {'declared_type': 'System.Int32',
                                                                                      'value': -1},
                                                 'RikidoBreakTransition.StartFrame': {'declared_type': 'System.Single',
                                                                                      'value': 0.0}},
 'app.motion_track.EnemyAttackGuideTrack': {'GuideType': {'declared_type': 'System.Int32',
                                                          'value': 10823},
                                            'GuideTypeOverrideByPLOniMode': {'declared_type': 'System.Int32',
                                                                             'value': 10823},
                                            'IsDisplay': {'declared_type': 'System.Boolean',
                                                          'value': False},
                                            'IsUseCustomDisplayPos': {'declared_type': 'System.Boolean',
                                                                      'value': False},
                                            'JointHash.Hash': {'declared_type': 'System.UInt32',
                                                               'value': 0}},
 'app.motion_track.EnemyBasic': {'CheckWaitAndSeeMove': {'declared_type': 'System.Boolean',
                                                         'value': False},
                                 'DissolveShapeJointHash.JointHash.Hash': {'declared_type': 'System.UInt32',
                                                                           'value': 0},
                                 'DissolveShapeScale': {'declared_type': 'System.Single',
                                                        'value': 1.0},
                                 'InvalidUpdateTargetPosOffFlag': {'declared_type': 'System.Boolean',
                                                                   'value': False},
                                 'NoGravityFlag': {'declared_type': 'System.Boolean',
                                                   'value': False},
                                 'PlayerDisableTargetTurnFlag': {'declared_type': 'System.Boolean',
                                                                 'value': False},
                                 'TargetJointHash.JointHash.Hash': {'declared_type': 'System.UInt32',
                                                                    'value': 0},
                                 'TargetRotate': {'declared_type': 'System.Single', 'value': 0.0},
                                 'TargetRotateOffset.OffsetY': {'declared_type': 'System.Single',
                                                                'value': 0.0},
                                 'TargetRotateOffset.PositionOffsetX': {'declared_type': 'System.Single',
                                                                        'value': 0.0},
                                 'TargetRotateOffset.Use': {'declared_type': 'System.Boolean',
                                                            'value': False},
                                 'WeaponCondition': {'declared_type': 'System.Int32',
                                                     'value': -1556110080}},
 'app.motion_track.EnemyTargetChangeableMove': {'BaseMoveDist': {'declared_type': 'System.Single',
                                                                 'value': 1.0},
                                                'IsChangeMove': {'declared_type': 'System.Boolean',
                                                                 'value': False},
                                                'MaxMoveDist': {'declared_type': 'System.Single',
                                                                'value': 1.0},
                                                'MinMoveDist': {'declared_type': 'System.Single',
                                                                'value': 1.0},
                                                'MoveType': {'declared_type': 'System.Int32',
                                                             'value': -774044608}},
 'app.motion_track.PlayerBasic': {'ActionFlag1': {'declared_type': 'System.Boolean',
                                                  'value': False},
                                  'ActionFlag2': {'declared_type': 'System.Boolean',
                                                  'value': False},
                                  'ActionTrg1': {'declared_type': 'System.Boolean', 'value': False},
                                  'ActionTrg2': {'declared_type': 'System.Boolean', 'value': False},
                                  'ActionTrg3': {'declared_type': 'System.Boolean', 'value': False},
                                  'ActionValue1': {'declared_type': 'System.Single', 'value': 0.0},
                                  'ActionValue2': {'declared_type': 'System.Single', 'value': 0.0},
                                  'AdjustGimmickAttach': {'declared_type': 'System.Single',
                                                          'value': 0.0},
                                  'AdjustGroundDir': {'declared_type': 'System.Boolean',
                                                      'value': False},
                                  'BodyKumiwazaDriverRate': {'declared_type': 'System.Single',
                                                             'value': 0.0},
                                  'BodyOverwriteChainGroupPresetID': {'declared_type': 'System.Int32',
                                                                      'value': -1},
                                  'DisableLockOnAutoSwitch': {'declared_type': 'System.Boolean',
                                                              'value': False},
                                  'DisableLockOnButton': {'declared_type': 'System.Boolean',
                                                          'value': False},
                                  'DisableLockOnSwitch': {'declared_type': 'System.Boolean',
                                                          'value': False},
                                  'DisableRikidoRecovary': {'declared_type': 'System.Boolean',
                                                            'value': False},
                                  'EnemyDisableUpdateTargetPosFlag': {'declared_type': 'System.Boolean',
                                                                      'value': False},
                                  'IsDisableFallAction': {'declared_type': 'System.Boolean',
                                                          'value': False},
                                  'IsDisableGroundAttach': {'declared_type': 'System.Boolean',
                                                            'value': False},
                                  'IsDisableLanding': {'declared_type': 'System.Boolean',
                                                       'value': False},
                                  'IsDisablePlayerMeshAlphaFade': {'declared_type': 'System.Boolean',
                                                                   'value': False},
                                  'IsFeintAttackDetect': {'declared_type': 'System.Boolean',
                                                          'value': False},
                                  'IsOniArmsOn': {'declared_type': 'System.Boolean',
                                                  'value': False},
                                  'IsOniLegsOn': {'declared_type': 'System.Boolean',
                                                  'value': False},
                                  'IsPlSkipContinue': {'declared_type': 'System.Boolean',
                                                       'value': False},
                                  'NoEmCombatContinue': {'declared_type': 'System.Boolean',
                                                         'value': False},
                                  'OverrideGravity': {'declared_type': 'System.Single',
                                                      'value': 13.0},
                                  'OverrideMotionSpeedRate': {'declared_type': 'System.Single',
                                                              'value': 0.0},
                                  'OverrideResistanceXZ': {'declared_type': 'System.Single',
                                                           'value': 4.0},
                                  'RikidoBreakEnd': {'declared_type': 'System.Boolean',
                                                     'value': False},
                                  'TurnRate': {'declared_type': 'System.Single', 'value': 0.0},
                                  'TurnSpeed': {'declared_type': 'System.Single', 'value': 0.0},
                                  'ZeroGravity': {'declared_type': 'System.Boolean',
                                                  'value': False},
                                  'ZeroGravity_GravityOnly': {'declared_type': 'System.Boolean',
                                                              'value': False}},
 'app.motion_track.PlayerCloakControlTrack': {'Chain2OverwriteGroupPresetID': {'declared_type': 'System.Int32',
                                                                               'value': -1},
                                              'JointConstraintsBrendRate_MantShoulder': {'declared_type': 'System.Single',
                                                                                         'value': -1.0},
                                              'OverwriteFrame': {'declared_type': 'System.Single',
                                                                 'value': 0.0},
                                              'OverwriteRate': {'declared_type': 'System.Single',
                                                                'value': -1.0}},
 'app.motion_track.PlayerCommandCancel': {'AbsorbCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                            'value': 0},
                                          'AbsorbStopCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'AttackBlowCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'AttackGroupCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                 'value': 0},
                                          'AttackHardCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'AttackHardChargeCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                      'value': 0},
                                          'AttackHardComboCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                     'value': 0},
                                          'AttackJustDodgeCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                     'value': 0},
                                          'AttackLightCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                 'value': 0},
                                          'AttackLightChargeCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                       'value': 0},
                                          'AttackLightComboCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                      'value': 0},
                                          'AttackSneakCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                 'value': 0},
                                          'BattleIdleCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'BlockCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                           'value': 0},
                                          'BowCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                         'value': 0},
                                          'DashAttack.ActionSelectType': {'declared_type': 'System.Int32',
                                                                          'value': 0},
                                          'DashAttack.InputContinueFrame': {'declared_type': 'System.Int32',
                                                                            'value': 15},
                                          'DashCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                          'value': 0},
                                          'DashKeepCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                              'value': 0},
                                          'DefenceGroupCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                  'value': 0},
                                          'DirectionTurn.ActionSelectType': {'declared_type': 'System.Int32',
                                                                             'value': 0},
                                          'DodgeCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                           'value': 0},
                                          'DodgeGroupCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'EdgeCatch.ActionSelectType': {'declared_type': 'System.Int32',
                                                                         'value': 0},
                                          'GrabCounterCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                 'value': 0},
                                          'GrappleBlowCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                 'value': 0},
                                          'GuardCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                           'value': 0},
                                          'GuardStopCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'IdleCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                          'value': 0},
                                          'InteractCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                              'value': 0},
                                          'InteractKeepCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                  'value': 0},
                                          'IssenBlockCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'IssenBreakCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'IssenChainCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'IssenCounterCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                  'value': 0},
                                          'IssenGroupCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'ItemCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                          'value': 0},
                                          'JustDodgeCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'JustGroupCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'LockOnCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                            'value': 0},
                                          'LoopInteractGimmickStopCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                             'value': 0},
                                          'MedicineCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                              'value': 0},
                                          'MenuGroupCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'MenuItemCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                              'value': 0},
                                          'MenuSkillCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'MoveGroupCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'OniChangeCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'OniEyeSonerCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                 'value': 0},
                                          'ParryCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                           'value': 0},
                                          'QuickStopCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'RunCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                         'value': 0},
                                          'RunTurnCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                             'value': 0},
                                          'Skill0ShotCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                'value': 0},
                                          'SkillCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                           'value': 0},
                                          'SkillKeepCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'StandIdleGroupCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                    'value': 0},
                                          'StrafeTurn.ActionSelectType': {'declared_type': 'System.Int32',
                                                                          'value': 0},
                                          'SubWeaponBowShotCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                      'value': 0},
                                          'UltimateAttackCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                                    'value': 0},
                                          'WalkCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                          'value': 0},
                                          'WalkKeepCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                              'value': 0},
                                          'WalkStickCancel.ActionSelectType': {'declared_type': 'System.Int32',
                                                                               'value': 0},
                                          'Wall.ActionSelectType': {'declared_type': 'System.Int32',
                                                                    'value': 0}},
 'app.motion_track.PlayerSoulBoostSpawnShell': {'ExpansionWork': {'declared_type': 'System.Int32',
                                                                  'value': -1},
                                                'IsDirectWorldPos': {'declared_type': 'System.Boolean',
                                                                     'value': False},
                                                'IsUseTargetObject': {'declared_type': 'System.Boolean',
                                                                      'value': False},
                                                'OverwriteAttackParamID': {'declared_type': 'System.Int32',
                                                                           'value': -1},
                                                'ShellGroupNo': {'declared_type': 'System.Int32',
                                                                 'value': -1},
                                                'ShellID': {'declared_type': 'System.Int32',
                                                            'value': -1},
                                                'Spawn': {'declared_type': 'System.Boolean',
                                                          'value': False}},
 'app.motion_track.PlayerTrackingTarget': {'Enable': {'declared_type': 'System.Boolean',
                                                      'value': False},
                                           'IsRayCheckAdjust': {'declared_type': 'System.Boolean',
                                                                'value': False},
                                           'IsTargetCounterIssen': {'declared_type': 'System.Boolean',
                                                                    'value': False},
                                           'MotionTransRate.x': {'declared_type': 'System.Single',
                                                                 'value': 1.0},
                                           'MotionTransRate.z': {'declared_type': 'System.Single',
                                                                 'value': 1.0},
                                           'MotionTransRateXZ': {'declared_type': 'System.Single',
                                                                 'value': 1.0},
                                           'MoveLimmit': {'declared_type': 'System.Single',
                                                          'value': 0.5},
                                           'MoveSpeed': {'declared_type': 'System.Single',
                                                         'value': 0.0},
                                           'OffsetDistance': {'declared_type': 'System.Single',
                                                              'value': 1.0},
                                           'RotLimit_Deg': {'declared_type': 'System.Single',
                                                            'value': 0.0},
                                           'SearchDistance': {'declared_type': 'System.Single',
                                                              'value': 2.0}},
 'app.motion_track.RikidoTiredBlendTrack': {'BlendRateSetting_Body.On': {'declared_type': 'System.Boolean',
                                                                         'value': False},
                                            'BlendRateSetting_Body.Rate': {'declared_type': 'System.Single',
                                                                           'value': 0.0},
                                            'BlendRateSetting_Head.On': {'declared_type': 'System.Boolean',
                                                                         'value': False},
                                            'BlendRateSetting_Head.Rate': {'declared_type': 'System.Single',
                                                                           'value': 0.0},
                                            'BlendRateSetting_LArm.On': {'declared_type': 'System.Boolean',
                                                                         'value': False},
                                            'BlendRateSetting_LArm.Rate': {'declared_type': 'System.Single',
                                                                           'value': 0.0},
                                            'BlendRateSetting_Lower.On': {'declared_type': 'System.Boolean',
                                                                          'value': False},
                                            'BlendRateSetting_Lower.Rate': {'declared_type': 'System.Single',
                                                                            'value': 0.0},
                                            'BlendRateSetting_RArm.On': {'declared_type': 'System.Boolean',
                                                                         'value': False},
                                            'BlendRateSetting_RArm.Rate': {'declared_type': 'System.Single',
                                                                           'value': 0.0},
                                            'DisableRikidoTired': {'declared_type': 'System.Boolean',
                                                                   'value': False},
                                            'KatanaHoldSetting.On': {'declared_type': 'System.Boolean',
                                                                     'value': False},
                                            'OverwriteParam': {'declared_type': 'System.Int32',
                                                               'value': 0}},
 'app.motion_track.SheathHold': {'AttachHokanFrame': {'declared_type': 'System.Int32', 'value': -1},
                                 'BlendRate': {'declared_type': 'System.Single', 'value': 0.0},
                                 'EndBlendFrame': {'declared_type': 'System.Int32', 'value': 20},
                                 'HoldOn': {'declared_type': 'System.Boolean', 'value': False},
                                 'IKRate': {'declared_type': 'System.Single', 'value': 0.0},
                                 'IsForceHold': {'declared_type': 'System.Boolean', 'value': False},
                                 'IsNoHokaningNoAttach': {'declared_type': 'System.Boolean',
                                                          'value': False},
                                 'IsSkipRArm': {'declared_type': 'System.Boolean', 'value': False},
                                 'IsSkipRiseArm': {'declared_type': 'System.Boolean',
                                                   'value': False},
                                 'IsSkipUpperBody': {'declared_type': 'System.Boolean',
                                                     'value': False},
                                 'LeftArmBlendRate': {'declared_type': 'System.Single',
                                                      'value': 1.0},
                                 'Rate': {'declared_type': 'System.Single', 'value': 0.0},
                                 'SheathBodyStateType': {'declared_type': 'System.Int32',
                                                         'value': -1036897024},
                                 'SheathPullRate': {'declared_type': 'System.Single', 'value': 0.0},
                                 'WeaponOnOff_IsKatana2Lwep': {'declared_type': 'System.Boolean',
                                                               'value': False},
                                 'WeaponOnOff_IsKatana4Lwep2Katana': {'declared_type': 'System.Boolean',
                                                                      'value': False},
                                 'WeaponOnOff_IsLwep2Saya': {'declared_type': 'System.Boolean',
                                                             'value': False},
                                 'WeaponOnOff_IsXRotate180From': {'declared_type': 'System.Boolean',
                                                                  'value': False},
                                 'WeaponOnOff_IsXRotate180To': {'declared_type': 'System.Boolean',
                                                                'value': False},
                                 'WeaponOnOff_RateKatana2Lwep': {'declared_type': 'System.Single',
                                                                 'value': 0.0},
                                 'WeaponOnOff_RateKatana4Lwep2Katana': {'declared_type': 'System.Single',
                                                                        'value': 0.0},
                                 'WeaponOnOff_RateLwep2Saya': {'declared_type': 'System.Single',
                                                               'value': 0.0}},
 'app.motion_track.cVfxOverwriteParam': {'AdditionalBreakableVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                               'value': False},
                                         'AdditionalBreakableVfx.On': {'declared_type': 'System.Boolean',
                                                                       'value': False},
                                         'AdditionalBreakableVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                            'value': True},
                                         'AdditionalBreakableVfx.Value.ElementId': {'declared_type': 'System.UInt32',
                                                                                    'value': 0},
                                         'AdditionalBreakableVfx.Value.EpvsId': {'declared_type': 'System.UInt32',
                                                                                 'value': 0},
                                         'AdditionalElementVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                             'value': False},
                                         'AdditionalElementVfx.On': {'declared_type': 'System.Boolean',
                                                                     'value': False},
                                         'AdditionalElementVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                          'value': True},
                                         'AdditionalElementVfx.Value.ElementId': {'declared_type': 'System.UInt32',
                                                                                  'value': 0},
                                         'AdditionalElementVfx.Value.EpvsId': {'declared_type': 'System.UInt32',
                                                                               'value': 0},
                                         'AdditionalNormalHitVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                               'value': False},
                                         'AdditionalNormalHitVfx.On': {'declared_type': 'System.Boolean',
                                                                       'value': False},
                                         'AdditionalNormalHitVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                            'value': True},
                                         'AdditionalNormalHitVfx.Value.ElementId': {'declared_type': 'System.UInt32',
                                                                                    'value': 0},
                                         'AdditionalNormalHitVfx.Value.EpvsId': {'declared_type': 'System.UInt32',
                                                                                 'value': 0},
                                         'AdditionalSoulGenerateVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                                  'value': False},
                                         'AdditionalSoulGenerateVfx.On': {'declared_type': 'System.Boolean',
                                                                          'value': False},
                                         'AdditionalSoulGenerateVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                               'value': True},
                                         'AdditionalSoulGenerateVfx.Value.ElementId': {'declared_type': 'System.UInt32',
                                                                                       'value': 0},
                                         'AdditionalSoulGenerateVfx.Value.EpvsId': {'declared_type': 'System.UInt32',
                                                                                    'value': 0},
                                         'AdditionalVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                      'value': False},
                                         'AdditionalVfx.On': {'declared_type': 'System.Boolean',
                                                              'value': False},
                                         'AdditionalVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                   'value': True},
                                         'AdditionalVfx.Value.ElementId': {'declared_type': 'System.UInt32',
                                                                           'value': 0},
                                         'AdditionalVfx.Value.EpvsId': {'declared_type': 'System.UInt32',
                                                                        'value': 0},
                                         'BaseVfx.On': {'declared_type': 'System.Boolean',
                                                        'value': False},
                                         'BaseVfx.Value.ElementId': {'declared_type': 'System.UInt32',
                                                                     'value': 0},
                                         'BaseVfx.Value.EpvsId': {'declared_type': 'System.UInt32',
                                                                  'value': 0},
                                         'BloodTrail.AttachInfo.On': {'declared_type': 'System.Boolean',
                                                                      'value': False},
                                         'BloodTrail.AttachInfo.WeaponType': {'declared_type': 'System.Int32',
                                                                              'value': 15},
                                         'BloodTrail.On': {'declared_type': 'System.Boolean',
                                                           'value': False},
                                         'BloodTrail.VfxId.On': {'declared_type': 'System.Boolean',
                                                                 'value': False},
                                         'DlcAdditionalHitVfx.DisableVfx': {'declared_type': 'System.Boolean',
                                                                            'value': False},
                                         'DlcAdditionalHitVfx.On': {'declared_type': 'System.Boolean',
                                                                    'value': False},
                                         'DlcAdditionalHitVfx.ShowVfx': {'declared_type': 'System.Boolean',
                                                                         'value': True},
                                         'DlcAdditionalHitVfx.Value.ElementId': {'declared_type': 'System.UInt32',
                                                                                 'value': 0},
                                         'DlcAdditionalHitVfx.Value.EpvsId': {'declared_type': 'System.UInt32',
                                                                              'value': 0},
                                         'Position.On': {'declared_type': 'System.Boolean',
                                                         'value': False},
                                         'Position.Random': {'declared_type': 'System.Boolean',
                                                             'value': False},
                                         'Position.RandomValue': {'declared_type': 'System.Single',
                                                                  'value': 0.0},
                                         'Position.UseJointConst': {'declared_type': 'System.Boolean',
                                                                    'value': False},
                                         'Rotation.On': {'declared_type': 'System.Boolean',
                                                         'value': False},
                                         'Rotation.Random': {'declared_type': 'System.Boolean',
                                                             'value': False},
                                         'Scale.On': {'declared_type': 'System.Boolean',
                                                      'value': False},
                                         'Scale.Random': {'declared_type': 'System.Boolean',
                                                          'value': False},
                                         'Scale.RandomValue': {'declared_type': 'System.Single',
                                                               'value': 0.0},
                                         'Scale.Value': {'declared_type': 'System.Single',
                                                         'value': 1.0}}}

RESET_DIFFERENCES = {'app.motion_track.AttackCollision_Body': {'HitStopID': [0, 1],
                                           'OnClipBox.On': [False],
                                           'ReachPatternIDOverride': [-1, 100],
                                           'RequestSetID': [36, 2001, 0, 2, 3]},
 'app.motion_track.AttackCollision_Wp': {'CollisionType': [0, 2],
                                         'HitStopID': [0, 1],
                                         'OnClipBox.On': [False],
                                         'RequestSetID': [0, 11, 1, 3]},
 'app.motion_track.CameraEvent': {'CameraAutoFollowDisable': [False],
                                  'CameraLockOnDisable': [False]},
 'app.motion_track.CharacterHitStopTrack': {'HitStopAll.On': [False],
                                            'HitStopAllSp.On': [False],
                                            'HitStopOwner.On': [False],
                                            'HitStopOwnerTarget.On': [False],
                                            'HitStopOwnerTargetSp.On': [False],
                                            'HitStopTarget.On': [False]},
 'app.motion_track.EnemyActionTransitionTrack': {'DieFadeOut': [False]},
 'app.motion_track.PlayerBasic': {'OverrideMotionSpeedRate': [1.0], 'TurnRate': [1.0]},
 'app.motion_track.PlayerSoulBoostSpawnShell': {'OverwriteAttackParamID': [-1,
                                                                           1,
                                                                           2,
                                                                           3,
                                                                           56,
                                                                           57,
                                                                           6,
                                                                           53,
                                                                           54,
                                                                           4,
                                                                           5]},
 'app.motion_track.SheathHold': {'BlendRate': [1.0],
                                 'EndBlendFrame': [-1],
                                 'IKRate': [1.0],
                                 'Rate': [-1.0],
                                 'SheathPullRate': [-1.0]}}
